server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://39.97.180.17:3306/petshelter?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: jyang285

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: ca.mcgill.ecse321.petshelter.entity